# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba536b47a26e0fd8babb187d7a91887bd66be789fcd45ee23ad8ed0b6a7486c5a12db8e7b69be1514bb6b5dda526b6701803ba3ffecfb631b782cea3754d3fe

test:
  secret_key_base: e7e4fa1956a75af693cf3af3a09c658bf87c93e4e8957c2482c51180257a2773602b54f9dbea6675b430e1d3026fec1fee06914765a98d1911b4078cb88a72b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
